initial
ashok2009it/indigital_interns pull request #3
Opened 2023-04-06 09:17 UTC by Shilbha

Adds a new page "attendance.html"

2023-04-10 04:35 UTC, ashok2009it requested changes
@Shilbha san, attendance.htm is missing, please update it

2023-04-10 05:29 UTC, Shilbha commented
changes made

2023-04-24 11:18 UTC, ashok2009it approved these changes

2023-04-24 11:18 UTC, ashok2009it commented on Assests/script.js
> +   const labels = ["Present", "Absent"];
@Shilbha san, Please removed unnecessary code from this file, rest of things looks good

2023-04-24 11:18 UTC, merged